deploy-rinkeby: 
	npx hardhat run --network rinkeby scripts/deploy.js

compile: 
	npx hardhat compile

console: 
	npx hardhat console --network rinkeby

verify: 
	npx hardhat verify --network rinkeby 0x4167073492E21cbE915309053844e6b1E094366E 2686

install: 
	yarn add hardhat-etherscan

test: 
	npx hardhat test lottery-test.js